### ISSUE TITLE
Home directory is stuck in read only.

### ISSUE THREAD

**Issue by sequelwp** [pymumu/jailed-shell#11]
Hello,

I'm having a small issue where for a jailshell user, I cannot make their /home/USER directory writable. 

control:~ $ touch 1                                                                                                                                    
touch: cannot touch '1': Read-only file system

I've tried everything from using a bind (with rw flag) to adjusting the namespace config. The only thing that works is using uts in the config, but that gives access to far more than I wanted to. 

Is there a way to make the home directory read / writable for this user?

**Comment by KHIT93** [comment]
From what I have found, you need to define it like this:

```
bind /home/USER /home/USER rw,nodev,noexec,nosuid
```

That is at least what has worked for me

**Comment by sequelwp** [comment]
Thats one of the config's I've used, unfortunately not dice:

touch: cannot touch '1': Read-only file system
