### ISSUE TITLE
file not found through root user

### ISSUE THREAD

**Issue by kaustuva** [pymumu/jailed-shell#2]
hi

i can upload files into the home directory through jailed user. I can add/remove files/directories too. But i couldnt find same file/directory through system root user. I searched the uploaded file name across the file system but didnt find it through system root user. My idea is to link sftp user home directory to a mounted volume. please assist

Regards

**Comment by pymumu** [comment]
There is a description of the directories here.
https://github.com/pymumu/jail-shell#file-directory-description

for your requirements, you can use the following configuration
```shell
bind /opt/upload/%u /opt/upload ro,nodev,noexec,nosuid
```
the /opt/upload directory in jail will be mapped to /opt/upload/[user]

for more, please read here: https://github.com/pymumu/jail-shell#jail-config-file-format-description

**Comment by kaustuva** [comment]
thank you @pymumu
